### ISSUE TITLE
Translation function does not return anything.

### ISSUE THREAD

**Issue by alberto-portilla** [DotZecker/zelcat#3]
I mean, what the fuck?

**Comment by rgomezcasas** [comment]
Hola, @alberto-portilla, si no em parles en català no m'entero.

**Comment by alberto-portilla** [comment]
Ho sento, volia dir que la funció de traducció retorna el mateix text que li introdueixes.

**Comment by rgomezcasas** [comment]
Clar, @alberto-portilla, però si no fossis tan xarrupaescrots et donaries compte de què està wip

**Comment by alberto-portilla** [comment]
Al dock bloc no diu res d'això. Això vol dir que no serà solucionat? Li trec l'estrella al repositori.
